mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

spring:
  datasource:
    driverClassNam: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/focus?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redisson:
    #address: redis://192.168.242.128:6379
    address: redis://127.0.0.1:6379
  profiles:
    active: dev
  application:
    name: spring-cloud-focus

server:
  port: 8080